### ISSUE TITLE
panic when trying to diagnose a service with unreconciled ingress

### ISSUE THREAD

**Issue by maximilien** [knative-sandbox/kn-plugin-diag#35]
# What 

I get a go panic dump when I tried to use `kn-diag` to diagnose a service which is failing with "IngressNotConfigured: Ingress has not yet been reconciled". This is the dump:

```bash
➜  kn-plugin-diag git:(main) ✗ ./kn-diag service hello
Failed to load the status.conditions for kingress hello, <nil>
Resource Type                              | Name                                  | Created At              | Status.Condition
panic: strings: negative Repeat count

goroutine 1 [running]:
strings.Repeat(0x22d44b8, 0x1, 0xffffffffffffffdb, 0xc000221740, 0x2b)
	/usr/local/Cellar/go/1.16.3/libexec/src/strings/strings.go:529 +0x5e5
knative.dev/kn-plugin-diag/pkg/utils.(*PrintableTable).PrintDump(0xc000198380, 0xc00000ff01, 0x0, 0x0, 0xc000198380)
	/Users/maximilien/github/knative-sandbox/src/github/knative-sandbox/kn-plugin-diag/pkg/utils/table.go:111 +0x897
knative.dev/kn-plugin-diag/pkg/utils.(*PrintableTable).Print(0xc000198380)
	/Users/maximilien/github/knative-sandbox/src/github/knative-sandbox/kn-plugin-diag/pkg/utils/table.go:146 +0x34
knative.dev/kn-plugin-diag/pkg/command/diagnose.dumpToTables(0xc000113e00, 0x0, 0x0, 0x0, 0x0)
	/Users/maximilien/github/knative-sandbox/src/github/knative-sandbox/kn-plugin-diag/pkg/command/diagnose/service.go:92 +0x1d7
knative.dev/kn-plugin-diag/pkg/command/diagnose.NewServiceCmd.func2(0xc0004d2500, 0xc000218b40, 0x1, 0x1, 0x0, 0x0)
	/Users/maximilien/github/knative-sandbox/src/github/knative-sandbox/kn-plugin-diag/pkg/command/diagnose/service.go:61 +0x129
github.com/spf13/cobra.(*Command).execute(0xc0004d2500, 0xc000218b10, 0x1, 0x1, 0xc0004d2500, 0xc000218b10)
	/Users/maximilien/github/knative-sandbox/src/github/knative-sandbox/kn-plugin-diag/vendor/github.com/spf13/cobra/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004d2000, 0xc0000dff60, 0x1, 0x1)
	/Users/maximilien/github/knative-sandbox/src/github/knative-sandbox/kn-plugin-diag/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/maximilien/github/knative-sandbox/src/github/knative-sandbox/kn-plugin-diag/vendor/github.com/spf13/cobra/command.go:897
main.main()
	/Users/maximilien/github/knative-sandbox/src/github/knative-sandbox/kn-plugin-diag/cmd/main.go:41 +0x105
```

# How

```bash
./kn-diag service hello
```

when service `hello` is failing with:

```bash
./kn service list                                      Michaels-MacBook-Pro.local: Wed May 12 15:24:49 2021

NAME     URL                                 LATEST          AGE     CONDITIONS   READY     REASON
hello    http://hello.default.example.com    hello-qgjrq-1   98d     1 OK / 3     Unknown   IngressNotConfigured : Ingr
ess has not yet been reconciled.
```

# Expected 

In the best case scenario, since this is a "diagnostic" plugin I would expect to have some diagnostic details on why the service is failing.

In the worst case scenario, I'd expect a message telling me the service is failing and more than "IngressNotConfigured : Ingr
ess has not yet been reconciled."

And in NO CASES a panic. That's a bug.

/kind bug

**Comment by cdlliuy** [comment]
yes,  @maximilien   I will check further and fix it.

**Comment by maximilien** [comment]
Fixed. Thanks @cdlliuy
